# Provides connection details for targets
# The environment variables needs to be exported in the CLI before starting the DBT
dbt_project:
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST') }}"
      user: "{{ env_var('DB_USER') }}"
      pass: "{{ env_var('DB_PASS') }}"
      port: "{{ env_var('DB_PORT') | int }}"
      dbname: "{{ env_var('DB_NAME') }}"
      schema: deepdarshak_staging
      threads: 4
  target: dev
